jobs:
  - name: daily
    targetName: dev
    schedule: 0 12 * * *
    timeout: 2h30m
    retryOnFailure: false
    steps:
      - name: run models
        command: dbt run

      - name: test models
        command: dbt test

  - name: nightly
    targetName: dev
    schedule: 0 0 * * *
    steps:
      - name: run selected models
        command: dbt run --select stg_transactions daily_revenue

  - name: weekdays
    targetName: dev
    schedule: 30 7 * * 1-5
    steps:
      - name: run models
        command: dbt run

  - name: every30minutes
    targetName: dev
    schedule: "*/30 * * * *"
    steps:
      - name: run models
        command: dbt run
